<h1>Proyecto sobre interpretabilidad sobre modelos de caja negra</h1>

<p>En este proyecto nos dedicaremos a realizar el entrenamiento para los modelos de interpretabilidad de modelos de caja negra,en nuestro proyecto hemos realizado hacer el entrenamiento de modelos para tareas de clasifiacacion. Adelante en esta practica primero realizaremos el entrenamiento de los diferentes modelos de caja negra primero realizaremos el entrenamiento a un modelo de redes neuronales.</p>
<u><b>A continuacion el siguiente bloque de codigo es necesario ejecutarlo para el correcto funcionamiento de este notebook.</b></u>

In [33]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import numpy as np
from tensorflow import get_logger
get_logger().setLevel('ERROR')
import random
from tensorflow import random as tensorflow_random

random.seed(2398572)
tensorflow_random.set_seed(394867)

import pandas
from sklearn import model_selection

np.random.seed(43958734)
np.set_printoptions(threshold=10)
from tensorflow import keras as ke

from scipy.spatial.distance import euclidean
from scipy.spatial.distance import cdist

<p>Ahora vamos a seleccionar el primer csv que contiene los datos y seleccionaremos los atributos que tendremos en cuenta para hacer el entrenamiento del algoritmo</p>

In [34]:
shill_bidding = pandas.read_csv("Shill Bidding Dataset.csv")
shill_bidding.head()

Record_ID  Auction_ID Bidder_ID  Bidder_Tendency  Bidding_Ratio  \
0          1         732     _***i         0.200000       0.400000   
1          2         732     g***r         0.024390       0.200000   
2          3         732     t***p         0.142857       0.200000   
3          4         732     7***n         0.100000       0.200000   
4          5         900     z***z         0.051282       0.222222   

   Successive_Outbidding  Last_Bidding  Auction_Bids  Starting_Price_Average  \
0                    0.0      0.000028           0.0                0.993593   
1                    0.0      0.013123           0.0                0.993593   
2                    0.0      0.003042           0.0                0.993593   
3                    0.0      0.097477           0.0                0.993593   
4                    0.0      0.001318           0.0                0.000000   

   Early_Bidding  Winning_Ratio  Auction_Duration  Class  
0       0.000028       0.666667                 5      0  
1       0.013123       0.944444                 5      0  
2       0.003042       1.000000                 5      0  
3       0.097477       1.000000                 5      0  
4       0.001242       0.500000                 7      0

Seleccionamos los atributos a tener encuenta a la hora de entrenar

In [35]:
atributos = shill_bidding.loc[:,'Bidder_Tendency':'Auction_Duration']
atributos = atributos.to_numpy()
print(atributos)


[[2.00000000e-01 4.00000000e-01 0.00000000e+00 ... 2.77778000e-05
  6.66666667e-01 5.00000000e+00]
 [2.43902440e-02 2.00000000e-01 0.00000000e+00 ... 1.31226852e-02
  9.44444444e-01 5.00000000e+00]
 [1.42857143e-01 2.00000000e-01 0.00000000e+00 ... 3.04166670e-03
  1.00000000e+00 5.00000000e+00]
 ...
 [5.55555560e-02 4.34782610e-02 0.00000000e+00 ... 1.56630291e-02
  0.00000000e+00 7.00000000e+00]
 [7.69230770e-02 8.69565220e-02 0.00000000e+00 ... 4.15013200e-04
  0.00000000e+00 7.00000000e+00]
 [1.63934430e-02 4.34782610e-02 0.00000000e+00 ... 3.40350529e-01
  0.00000000e+00 7.00000000e+00]]


<p>Vamos a seleccionar el atributo objetivo para el algoritmo</p>

In [138]:
objetivo = shill_bidding['Class']
objetivo = objetivo.to_numpy()
print(objetivo)

[0 0 0 ... 0 0 0]


Entrenamos el modelo de redes neuronales y dividimos el modelo de entrenamiento con el modelo de pruebas

In [144]:
(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = model_selection.train_test_split(
    atributos, objetivo, test_size=.2)


9
9


Input indica el numero de dimensiones y dense indica cantidad de neuronas y la funcion de activacion, que por defecto es la identidad. Este ejemplo es para modelos de <b>clasificacion</b> 

La red neuronal posee una única capa (aparte de la de entrada) que proporciona como salida un array bidimensional None x 1 (es decir, para cada ejemplo proporciona un valor) y 9 parámetros (el peso de la conexión de cada entrada con la neurona de la capa más el sesgo de la neurona) entrenables (la red los aprenderá mediante el algoritmo de entrenamiento).

In [38]:
red_bidding = ke.Sequential()
red_bidding.add(ke.Input(shape=(9,)))
red_bidding.add(ke.layers.Dense(10, activation='relu'))
red_bidding.add(ke.layers.Dense(1, activation='sigmoid'))

Los pesos y sesgos de la red se guardan en el atributo weights (son los arrays asociados al argumento numpy en la estructura de datos guardada en ese atributo).

In [39]:
red_bidding.summary()
red_bidding.weights

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 10)                100       
                                                                 
 dense_5 (Dense)             (None, 1)                 11        
                                                                 
Total params: 111
Trainable params: 111
Non-trainable params: 0
_________________________________________________________________


[<tf.Variable 'dense_4/kernel:0' shape=(9, 10) dtype=float32, numpy=
 array([[ 0.16066974, -0.1832436 , -0.3538186 , ...,  0.340855  ,
          0.25578886,  0.5128347 ],
        [-0.1894975 , -0.0651882 , -0.12789819, ..., -0.19957277,
         -0.0312627 , -0.17042843],
        [-0.4715354 , -0.20407248,  0.29305267, ..., -0.50047326,
          0.43153203,  0.34140068],
        ...,
        [-0.01709646, -0.03771824, -0.15322047, ...,  0.49320394,
          0.24029279, -0.05415136],
        [ 0.2125234 ,  0.41607064, -0.06427649, ..., -0.03796834,
          0.12062675,  0.19724232],
        [ 0.27244765,  0.48618132,  0.47343248, ...,  0.20641726,
          0.0910573 ,  0.37640864]], dtype=float32)>,
 <tf.Variable 'dense_4/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_5/kernel:0' shape=(10, 1) dtype=float32, numpy=
 array([[ 0.57531995],
        [ 0.17448515],
        [-0.48876932],
        [ 0.38587934]

Entrenamos la red neuronal con un optimizador y una funcion de perdida, en este caso al tratarse de un modelo de clasifiacion seleccionamos la funcion de perdida como la entropia cruzada binaria

In [40]:
red_bidding.compile(optimizer='SGD', loss='binary_crossentropy',
                   metrics=['accuracy'])

Aqui entrenamos el modelo con los atributos de prueba seleccionados y el objetivo de entrenamiento

In [41]:
red_bidding.fit(atributos_entrenamiento, objetivo_entrenamiento,
               batch_size=10, epochs=10)

Epoch 1/10
506/506 [==============================] - 1s 1ms/step - loss: 0.4077 - accuracy: 0.8728
Epoch 2/10
506/506 [==============================] - 1s 1ms/step - loss: 0.3151 - accuracy: 0.8934
Epoch 3/10
506/506 [==============================] - 1s 1ms/step - loss: 0.2429 - accuracy: 0.9120
Epoch 4/10
506/506 [==============================] - 1s 1ms/step - loss: 0.1768 - accuracy: 0.9456
Epoch 5/10
506/506 [==============================] - 1s 1ms/step - loss: 0.1307 - accuracy: 0.9608
Epoch 6/10
506/506 [==============================] - 1s 1ms/step - loss: 0.1028 - accuracy: 0.9636
Epoch 7/10
506/506 [==============================] - 1s 2ms/step - loss: 0.0861 - accuracy: 0.9654
Epoch 8/10
506/506 [==============================] - 1s 2ms/step - loss: 0.0766 - accuracy: 0.9650
Epoch 9/10
506/506 [==============================] - 1s 1ms/step - loss: 0.0697 - accuracy: 0.9689
Epoch 10/10
506/506 [==============================] - 1s 1ms/step - loss: 0.0660 - accuracy: 0.9711

Y ahora vamos a evaluar el modelo y ejecutar su prediccion con los atributos de prueba

In [42]:
red_bidding.evaluate(atributos_prueba, objetivo_prueba)
red_bidding.predict(atributos_prueba)
j = 0
vp=0
vn=0
fp=0
fn=0
for i in red_bidding.predict(atributos_prueba):
    
    if(i > 0.5):
        i = 1
    elif(i <= 0.5):
        i = 0
    if(i == objetivo_prueba[j] and i == 1):
        vp+=1
    elif(i !=objetivo_prueba[j] and i == 1):
        fp +=1
    elif(i ==objetivo_prueba[j] and i == 0):
        vn +=1
    elif(i !=objetivo_prueba[j] and i == 0):
        fn +=1
    j+=1
    
print("Buenos resultados:", vp+vn)
print("Malos resultados:", fp+fn)
print("La precision es: ", vp/(vp+fp))

40/40 [==============================] - 0s 974us/step
Buenos resultados: 1232
Malos resultados: 33
La precision es:  0.9369369369369369


In [43]:
wine_white = pandas.read_csv('winequality-white.csv', delimiter=";")
wine_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide    density    pH  sulphates  \
0                 45.0                 170.0  1001.0000  3.00       0.45   
1                 14.0                 132.0     0.9940  3.30       0.49   
2                 30.0                  97.0     0.9951  3.26       0.44   
3                 47.0                 186.0     0.9956  3.19       0.40   
4                 47.0                 186.0     0.9956  3.19       0.40   

   alcohol quality  
0      8.8   bueno  
1      9.5   bueno  
2     10.1   bueno  
3      9.9   bueno  
4      9.9   bueno

In [44]:
atributos1 = wine_white[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]
atributos1 = atributos1.to_numpy()

objetivo = wine_white[['quality']]
objetivo = pandas.get_dummies(objetivo)
print(objetivo)
objetivo = objetivo.to_numpy().astype(float)

(atributos_entrenamiento, atributos_prueba,
 objetivo_entrenamiento, objetivo_prueba) = model_selection.train_test_split(
    atributos1, objetivo, test_size=.2)

      quality_bueno  quality_decente  quality_excelente  quality_malo  \
0                 1                0                  0             0   
1                 1                0                  0             0   
2                 1                0                  0             0   
3                 1                0                  0             0   
4                 1                0                  0             0   
...             ...              ...                ...           ...   
4893              1                0                  0             0   
4894              0                1                  0             0   
4895              1                0                  0             0   
4896              0                0                  0             0   
4897              1                0                  0             0   

      quality_muy bueno  quality_perfecto  quality_regular  
0                     0                 0                0  
1

In [45]:
red_vino = ke.Sequential()
red_vino.add(ke.Input(shape=(11,)))
red_vino.add(ke.layers.Dense(10, activation='relu'))
# Aquie tantas neuronas como posibles clases
red_vino.add(ke.layers.Dense(7, activation='softmax'))

# Softmax es mejor activacion en clasificacion multiclase debido a que las
# probabilidades de todas las clases sumadas dan 1


In [46]:
red_vino.summary()
red_vino.weights

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                120       
                                                                 
 dense_7 (Dense)             (None, 7)                 77        
                                                                 
Total params: 197
Trainable params: 197
Non-trainable params: 0
_________________________________________________________________


[<tf.Variable 'dense_6/kernel:0' shape=(11, 10) dtype=float32, numpy=
 array([[ 0.4539268 , -0.07710254,  0.15135956, ..., -0.16307437,
          0.01278824,  0.11068517],
        [ 0.05725986,  0.23043233, -0.40509826, ...,  0.21256512,
         -0.00953633, -0.43251088],
        [ 0.29988438, -0.3497378 ,  0.30682307, ..., -0.19849265,
         -0.49182558,  0.01923186],
        ...,
        [ 0.4283719 , -0.33114657, -0.39846885, ..., -0.27326483,
         -0.18029127,  0.5209586 ],
        [-0.38899636,  0.22119498,  0.16854131, ..., -0.24828452,
          0.11630654,  0.33638996],
        [-0.20374537,  0.20948946, -0.01595587, ..., -0.14216772,
         -0.21667987,  0.08175027]], dtype=float32)>,
 <tf.Variable 'dense_6/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_7/kernel:0' shape=(10, 7) dtype=float32, numpy=
 array([[-0.2849492 ,  0.10531801,  0.44416118, ...,  0.08467072,
         -0.23218483,  

In [47]:
import tensorflow as tf
red_vino.compile( optimizer='SGD', loss='categorical_crossentropy',
                   metrics=['accuracy'])


red_vino.fit(atributos_entrenamiento, objetivo_entrenamiento,
               batch_size=10, epochs=10)

red_vino.evaluate(atributos_prueba, objetivo_prueba)
predictions = red_vino.predict(atributos_prueba)
# Esto lo realizamos para poder visualizar una aproximacion
for prediction, true_label in zip(predictions, objetivo_prueba):
    print("Prediccion: ", prediction, "Etiqueta real:", true_label)
    
# Realizar un algoritm que coja el indice del maximo de la lista y que devuelva un 1 en ese lugar

Epoch 1/10
392/392 [==============================] - 1s 1ms/step - loss: 9226.3105 - accuracy: 0.4364
Epoch 2/10
392/392 [==============================] - 0s 1ms/step - loss: 1.4778 - accuracy: 0.4525
Epoch 3/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3924 - accuracy: 0.4525
Epoch 4/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3561 - accuracy: 0.4525
Epoch 5/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3367 - accuracy: 0.4525
Epoch 6/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3253 - accuracy: 0.4525
Epoch 7/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3177 - accuracy: 0.4525
Epoch 8/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3126 - accuracy: 0.4525
Epoch 9/10
392/392 [==============================] - 0s 1ms/step - loss: 1.3090 - accuracy: 0.4525
Epoch 10/10
31/31 [==============================] - 0s 1ms/step
Prediccion:  [0.4480387  0.28931

 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.0

Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 0. 0. 0. 1. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426

 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 0. 0. 0. 1. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 0. 1. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.0

 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 0. 0. 0. 1. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [0. 1. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.03394386 0.01670838 0.16529194 0.0154112
 0.03129426] Etiqueta real: [1. 0. 0. 0. 0. 0. 0.]
Prediccion:  [0.4480387  0.28931168 0.0

# El siguiente modelo a realizar es random forest 

In [48]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [49]:
# Cargar el archivo CSV
data = pandas.read_csv('Shill Bidding Dataset.csv')

# Separar los atributos (X) y el objetio (y)
# Ajusta 'etiqueta' al nombre de la columna objetivo
X = data[['Bidder_Tendency','Bidding_Ratio', 'Successive_Outbidding', 'Last_Bidding','Auction_Bids', 'Starting_Price_Average', 'Early_Bidding','Winning_Ratio', 'Auction_Duration']]
X = X.to_numpy()
y = data['Class']
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# n_stimators = numero de arboles y max_depth profundidad maxima de cada arbol 
randomForest_Bidding = RandomForestClassifier(n_estimators=100, max_depth=10)
print(X)

[[2.00000000e-01 4.00000000e-01 0.00000000e+00 ... 2.77778000e-05
  6.66666667e-01 5.00000000e+00]
 [2.43902440e-02 2.00000000e-01 0.00000000e+00 ... 1.31226852e-02
  9.44444444e-01 5.00000000e+00]
 [1.42857143e-01 2.00000000e-01 0.00000000e+00 ... 3.04166670e-03
  1.00000000e+00 5.00000000e+00]
 ...
 [5.55555560e-02 4.34782610e-02 0.00000000e+00 ... 1.56630291e-02
  0.00000000e+00 7.00000000e+00]
 [7.69230770e-02 8.69565220e-02 0.00000000e+00 ... 4.15013200e-04
  0.00000000e+00 7.00000000e+00]
 [1.63934430e-02 4.34782610e-02 0.00000000e+00 ... 3.40350529e-01
  0.00000000e+00 7.00000000e+00]]


In [50]:
# Entrenamos el modelo con los datos
randomForest_Bidding.fit(X_train, y_train )

RandomForestClassifier(max_depth=10)

In [51]:
predictions = randomForest_Bidding.predict(X_test)
# Esto lo realizamos para poder visualizar una aproximacion

vp=0
vn=0
fp=0
fn=0
for prediction, true_label in zip(predictions, y_test):
    if(prediction == true_label and prediction == 1  ):
        vp+=1
    elif(prediction != true_label and prediction == 1):
        fp +=1
    elif(prediction == true_label and prediction == 0):
        vn +=1
    elif(prediction != true_label and prediction == 0):
        fn +=1

        
print("Buenos resultados:", vp+vn)
print("Malos resultados:", fp+fn)
print("La precision es: ", vp/(vp+fp))


Buenos resultados: 1256
Malos resultados: 9
La precision es:  0.9424460431654677


In [52]:
# Cargar el archivo CSV
data = pandas.read_csv('winequality-white1.csv', delimiter=";")
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [53]:

# Separar los atributos (X) y el objetio (y)
# Ajusta 'etiqueta' al nombre de la columna objetivo
X = data[['fixed acidity','volatile acidity','citric acid','residual sugar','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol']]
X = X.to_numpy()
y = data['quality']
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# n_stimators = numero de arboles y max_depth profundidad maxima de cada arbol 
randomForest_vinos = RandomForestClassifier(n_estimators=100, max_depth=10)
print(X)

[[ 7.    0.27  0.36 ...  3.    0.45  8.8 ]
 [ 6.3   0.3   0.34 ...  3.3   0.49  9.5 ]
 [ 8.1   0.28  0.4  ...  3.26  0.44 10.1 ]
 ...
 [ 6.5   0.24  0.19 ...  2.99  0.46  9.4 ]
 [ 5.5   0.29  0.3  ...  3.34  0.38 12.8 ]
 [ 6.    0.21  0.38 ...  3.26  0.32 11.8 ]]


In [54]:
# Entrenamos el modelo con los datos
randomForest_vinos.fit(X_train, y_train )

RandomForestClassifier(max_depth=10)

In [55]:
predictions = randomForest_vinos.predict(X_test)
# Esto lo realizamos para poder visualizar una aproximacion
for prediction, true_label in zip(predictions, y_test):
    print("Prediccion: ", prediction, "Etiqueta real:", true_label)


Prediccion:  6 Etiqueta real: 7
Prediccion:  8 Etiqueta real: 8
Prediccion:  6 Etiqueta real: 8
Prediccion:  5 Etiqueta real: 5
Prediccion:  7 Etiqueta real: 7
Prediccion:  6 Etiqueta real: 6
Prediccion:  5 Etiqueta real: 5
Prediccion:  5 Etiqueta real: 4
Prediccion:  6 Etiqueta real: 6
Prediccion:  5 Etiqueta real: 5
Prediccion:  7 Etiqueta real: 7
Prediccion:  5 Etiqueta real: 5
Prediccion:  7 Etiqueta real: 7
Prediccion:  5 Etiqueta real: 6
Prediccion:  6 Etiqueta real: 5
Prediccion:  5 Etiqueta real: 5
Prediccion:  7 Etiqueta real: 8
Prediccion:  6 Etiqueta real: 5
Prediccion:  6 Etiqueta real: 7
Prediccion:  6 Etiqueta real: 6
Prediccion:  5 Etiqueta real: 6
Prediccion:  6 Etiqueta real: 7
Prediccion:  5 Etiqueta real: 5
Prediccion:  6 Etiqueta real: 5
Prediccion:  6 Etiqueta real: 8
Prediccion:  6 Etiqueta real: 5
Prediccion:  5 Etiqueta real: 5
Prediccion:  6 Etiqueta real: 6
Prediccion:  7 Etiqueta real: 7
Prediccion:  5 Etiqueta real: 5
Prediccion:  5 Etiqueta real: 5
Predicci

# Este es el modelo LIME de interpretabilidad de modelos de caja negra

Este es el modelo de Lime que funciona podemos modificarlo averiguando la distancia con otro calculo como el de arriba y haciendo llamdas recursivas a funciones auxiliares

In [24]:
#Version 1 / Casi
def perturb(datos, cabecera):
    k = random.randint(1, len(datos))
    datos_perturbados = datos.copy()
    for j in range(k):
        atributo_a_perturbar = random.randint(0,len(datos)-1)
        rango_maximo = abs(max(a[atributo_a_perturbar] for a in cabecera))
        rango_minimo = abs(min(a[atributo_a_perturbar] for a in cabecera))
        datos_perturbados[atributo_a_perturbar] = random.uniform(rango_minimo, rango_maximo)
    return datos_perturbados

def obtener_indice_maximo(arr):
    max_valor = float('-inf')  # Inicializamos el valor máximo como el mínimo posible
    max_indice = None  # Inicializamos el índice máximo como None

    for i in range(len(arr)):
        if arr[i] > max_valor:
            max_valor = arr[i]
            max_indice = i

    return max_indice


In [120]:
# Cabe destacar que para que el comportamiento del modelo no sea aleatorio conviene inicializar la semilla siempre 
# En el mismo lougar
def explicacion_del_modelo(N,f,datos, cabecera):
    random.seed(2398572)
    tensorflow_random.set_seed(394867)
    X = [] # Muestras perturbadas
    R = [] # Representaciones
    W = [] # Distancias entre muestra x y sus perturbaciones
    for i in range(N):
        datos_perturbados= perturb(datos, cabecera)
        w = abs(sum(datos[atributo] - datos_perturbados[atributo] for atributo in range(0, len(datos)-1)))
        r = [0 if datos_perturbados[atributo] == datos[atributo] else 1 for atributo in range(0,len(datos)-1)]
        X.append(datos_perturbados)
        R.append(r)
        W.append(w)
    Y_perturbada = []
    for i in range(len(X)):
        if(isinstance(f,ke.Sequential)):
            x = X[i]
            array = np.array(x)
            x = array.reshape(1,-1)
            y = f.predict(x, verbose=0)
            if(len(y[0])>1): # Si nos encontramos con clasificacion multiclase, para averiguar la clase mas probable
                y = obtener_indice_maximo(y[0])
        else:
            x = X[i]
            array = np.array(x)
            x = array.reshape(1,-1)
            y = f.predict(x)

        Y_perturbada = np.append(Y_perturbada, y)  # Corrected line

    
    Y_perturbada = np.squeeze(Y_perturbada)
    G = Ridge()
    G.fit(R, Y_perturbada, sample_weight=W)
    pesos = G.coef_
    
    return pesos

In [121]:
params = explicacion_del_modelo(10, randomForest_Bidding, atributos[5809], atributos)

print(params)
print("--------------------------------")
params = explicacion_del_modelo(10, randomForest_Bidding, atributos[5809], atributos)

print(params)
print("--------------------------------")
params = explicacion_del_modelo(10, randomForest_Bidding, atributos[5809], atributos)

print(params)


[-0.31057341  0.21587797  0.00488666  0.21890333 -0.08763765  0.
 -0.14029631  0.25540856]
--------------------------------
[-0.31057341  0.21587797  0.00488666  0.21890333 -0.08763765  0.
 -0.14029631  0.25540856]
--------------------------------
[-0.31057341  0.21587797  0.00488666  0.21890333 -0.08763765  0.
 -0.14029631  0.25540856]


In [122]:
parametros = explicacion_del_modelo(10, red_bidding, atributos[5809], atributos)
print("Parametros de la 1ª muestra:")
print(parametros)
print("--------------------------------")
parametros = explicacion_del_modelo(10, red_bidding, atributos[5809], atributos)
print("Parametros de la 1ª muestra:")
print(parametros)
print("--------------------------------")
parametros = explicacion_del_modelo(10, red_bidding, atributos[5809], atributos)
print("Parametros de la 1ª muestra:")
print(parametros)
print("--------------------------------")

[0.04       0.03846154 0.95957171 0.25155093 0.47885099 0.
 0.25155093 0.         2.41544576]
[0.30610509 0.62271616 0.66781932 0.46890687 0.30769231 0.
 0.25155093 0.         7.        ]
[0.04       0.03846154 0.5689398  0.25155093 0.29770546 0.
 0.77027643 0.14664181 7.        ]
[0.04       0.03846154 0.         0.25155093 0.30769231 0.
 0.25155093 0.32535663 7.        ]
[0.04       0.14798379 0.92591605 0.78229848 0.30769231 0.
 0.25155093 0.89639028 7.        ]
[0.26795812 0.03846154 0.         0.34874971 0.48062421 0.
 0.25155093 0.         8.88541432]
[0.55282917 0.03846154 0.         0.21063014 0.30769231 0.
 0.25155093 0.         3.0119791 ]
[0.20924571 0.99813427 0.         0.34543236 0.07683329 0.
 0.29677217 0.         8.43316136]
[0.44466908 0.03846154 0.11017366 0.98374363 0.48281117 0.
 0.76683521 0.58179016 7.        ]
[0.29266743 0.03846154 0.         0.25155093 0.24598351 0.
 0.11411088 0.         7.        ]
Parametros de la 1ª muestra:
[-0.29153818  0.15721294  0.195

In [132]:
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.linear_model import Ridge

# Ejemplo utilizando el modelo "red_bidding" definido en el código anterior
parametros = explicacion_del_modelo(10, red_bidding, atributos[5809], atributos)
params = explicacion_del_modelo(10, randomForest_Bidding, atributos[5809], atributos)
print("Parametros de la 1ª muestra:")


print("Red apuestas: ")
print(parametros)
print("--------------------------------")

   

print("RandomForest Apuestas: ")
print(params)


params = explicacion_del_modelo(10, randomForest_vinos, atributos1[4809], atributos1)
parametros = explicacion_del_modelo(10, red_vino, atributos1[4809], atributos1)
print("Parametros de la 2ª muestra:")

    

print("Red vinos: ")
print(parametros)
print("--------------------------------")


print("RandomForest Vinos: ")
print(params)

[array([0.04      , 0.03846154, 0.95957171, 0.25155093, 0.47885099,
       0.        , 0.25155093, 0.        , 2.41544576]), array([0.30610509, 0.62271616, 0.66781932, 0.46890687, 0.30769231,
       0.        , 0.25155093, 0.        , 7.        ]), array([0.04      , 0.03846154, 0.5689398 , 0.25155093, 0.29770546,
       0.        , 0.77027643, 0.14664181, 7.        ]), array([0.04      , 0.03846154, 0.        , 0.25155093, 0.30769231,
       0.        , 0.25155093, 0.32535663, 7.        ]), array([0.04      , 0.14798379, 0.92591605, 0.78229848, 0.30769231,
       0.        , 0.25155093, 0.89639028, 7.        ]), array([0.26795812, 0.03846154, 0.        , 0.34874971, 0.48062421,
       0.        , 0.25155093, 0.        , 8.88541432]), array([0.55282917, 0.03846154, 0.        , 0.21063014, 0.30769231,
       0.        , 0.25155093, 0.        , 3.0119791 ]), array([0.20924571, 0.99813427, 0.        , 0.34543236, 0.07683329,
       0.        , 0.29677217, 0.        , 8.43316136]), array([

<p><strong>Alpha:</strong> Este parámetro controla la fuerza de la regularización en el modelo Ridge. Cuanto mayor sea el valor de alpha, mayor será la penalización aplicada a los coeficientes. Un valor de alpha igual a 1.0 indica una regularización moderada.</p>

<p><strong>Copy_X:</strong> Es un parámetro booleano que indica si los datos de entrada deben ser copiados antes de ajustar el modelo. Si se establece en True, se realiza una copia de los datos; si se establece en False, los datos se sobrescriben.</p>

<p><strong>Fit_intercept:</strong> Es un parámetro booleano que indica si se debe ajustar un intercepto en el modelo. Si se establece en True, el modelo incluirá un término constante; si se establece en False, el modelo no incluirá un término constante.</p>

<p><strong>Max_iter:</strong> Es el número máximo de iteraciones permitidas durante el ajuste del modelo. Si se establece en None, el modelo ajustará hasta que la convergencia sea alcanzada.</p>

<p><strong>Positive:</strong> Es un parámetro booleano que indica si los coeficientes deben ser no negativos. Si se establece en True, se restringe que los coeficientes sean siempre positivos.</p>

<p><strong>Random_state:</strong> Este parámetro controla la semilla utilizada por el generador de números aleatorios. Si se establece en None, el generador de números aleatorios utilizará una semilla diferente en cada ejecución.</p>

<p><strong>Solver:</strong> Especifica el algoritmo a utilizar en el ajuste del modelo. Si se establece en 'auto', el modelo seleccionará automáticamente el mejor algoritmo según los datos y el problema en cuestión.</p>

<p><strong>Tol:</strong> Especifica la tolerancia para el criterio de parada en el ajuste del modelo. Si la diferencia entre dos iteraciones consecutivas es menor que la tolerancia, el ajuste se considera convergido.</p>

<p><strong>Coef_:</strong> Especifica el peso que en esta caso se trata de la importancia de cada atributo a la hora de tomar decisiones para clasificar las muestras</p>


# Aqui tenemos los calculos requeridos sobre el trabajo

 <h1>Resumen de cálculos</h1>

  <i><b>1. Identidad:</b></i>
  <p>Verifica si las explicaciones son idénticas para objetos idénticos.</p>

 <i><b>2. Separabilidad:</b></i>
  <p>Verifica que las explicaciones sean diferentes para objetos no idénticos.</p>

 <i><b>3. Estabilidad:</b></i>
  <p>Evalúa si objetos similares tienen explicaciones similares mediante la correlación de Spearman.</p>

  <i><b>4. Selectividad:</b></i>
  <p>Mide el efecto de eliminar variables relevantes en la predicción mediante el cálculo del área bajo la curva (AUC).</p>

  <i><b>5. Completitud (Coherencia):</b></i>
  <p>Calcula la coherencia de una muestra al eliminar características no importantes.</p>

  <i><b>6. Completitud (Coherencia / Explicación):</b></i>
  <p>Calcula la coherencia promedio y la desviación estándar de la coherencia.</p>

 <i><b>7. Completitud (Congruencia):</b></i>
  <p>Calcula la desviación estándar de la coherencia como un proxy de congruencia.</p>


In [227]:
from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_auc_score
def identidad_(muestraA, muestraB, explicacionA, explicacionB):
    res = False
    distancia = np.linalg.norm(muestraA-muestraB)
    if distancia == 0:
        res = np.linalg.norm(explicacionA - explicacionB) == 0
    return res

def separabilidad_(muestraA, muestraB, explicacionA, explicacionB):
    res = False
    distancia = np.linalg.norm(muestraA-muestraB)
    if distancia != 0:
        res = np.linalg.norm(explicacionA - explicacionB) != 0
    return res

def estabilidad_(muestraA, muestraB, explicacionA, explicacionB):
    # Calcula las distancias entre las muestras y las explicaciones
    dist_muestras = np.abs(muestraA - muestraB)
    dist_explicaciones = np.abs(explicacionA - explicacionB)

    # Calcula la correlación de Spearman
    rho, _ = spearmanr(dist_muestras, dist_explicaciones)

    # Verifica si la correlación es mayor que cero para cada elemento
    if np.all(rho > 0):
        return True
    else:
        return False

def selectividad_(muestras, n_caracteristicas, modelo):
    auc_scores=[]
    for i in range(n_caracteristicas):
        muestras_modificadas = np.copy(muestras)
        muestras_modificadas[:, i] = 0
        
        # Obtener las etiquetas binarias para la característica i
        y_true = np.where(muestras[:, i] == 0, 0, 1)
        y_true_binary = label_binarize(y_true, classes=np.unique(y_true))
        
        # Obtener las predicciones del modelo con la característica i eliminada
        y_score = modelo.predict(muestras_modificadas, verbose=0)
        
        # Calcular el área bajo la curva (AUC) y almacenarlo en auc_scores
        print(np.mean(auc_scores))
        if len(np.unique(y_true_binary)) > 1:
            auc_scores.append(roc_auc_score(y_true_binary, y_score))
    
    if auc_scores:
        selectividad = np.mean(auc_scores)
    else:
        selectividad = 0.0
    
    return selectividad

def coherencia_(prediccion_original, prediccion_nueva, objetivo):
    # Obtener las predicciones del modelo para la señal original y la nueva señal
    # Calcular el error de predicción para la señal original
    error_prediccion_original = np.abs(prediccion_original - objetivo)
    error_prediccion_nueva = np.abs(prediccion_nueva - objetivo)
    coherencia = np.abs(error_prediccion_original - error_prediccion_nueva)
    return coherencia
def completitud_(prediccion_original, explicacion_error , objetivo):
    error_prediccion = np.mean(np.abs(prediccion_original - objetivo))

    completitud = np.abs(explicacion_error / error_prediccion) 
    return completitud
    
def congruencia_(coherencia):
    #Congruencia
    alpha = np.mean(coherencia)  # alpha_values es una lista/array con los valores de coherencia alpha_i

    # Calcular la desviación estándar de la coherencia
    N = len(data)
    delta = np.sqrt(np.mean((coherencia - alpha)**2) / N)  # N es el número total de muestras
    return delta


In [206]:
# Escogemos 256 muestras de prueba para las metricas
muestras_apuestas = []
muestras_vinos = []
objetivo_apuestas = []
for i in range(0, 256):
    muestras_apuestas.append(atributos_prueba[i])
    objetivo_apuestas.append(objetivo_prueba[i])
    muestras_vinos.append(X_test[i])

muestras_apuestas = np.array(muestras_apuestas)
objetivo_apuestas = np.array(objetivo_apuestas)
muestras_vinos = np.array(muestras_vinos)
# Tener cuidado con lo que es atributos prueba y X_test si son del CSV que corresponde (Renombrar variables)

In [172]:
# Metricas con red de apuestas
ide = True 

for i in range(0, 256):
    ide &= identidad_(muestras_apuestas[i], muestras_apuestas[i], explicacion_del_modelo(10 , red_bidding, muestras_apuestas[i], atributos_prueba),  explicacion_del_modelo(10 , red_bidding, muestras_apuestas[i], atributos_prueba))    
    #print("Identidad: Hasta los " ,i+1, " primeros está en:", ide)
print(ide)

True


In [173]:
# Metricas con red de vinos# Este es el LIME que funciona
sep = True
for i in range(0, 255):
    sep &= separabilidad_(muestras_apuestas[i], muestras_apuestas[i+1], explicacion_del_modelo(10 , red_bidding, muestras_apuestas[i], atributos_prueba),  explicacion_del_modelo(10 , red_bidding, muestras_apuestas[i+1], atributos_prueba))
    #print("Separabilidad: Hasta los " ,i+1, " primeros está en:", sep)
print(sep)

True


In [174]:
# Metricas con randomForest de apuestas
est = True
for i in range(0, 255):
    for j in range(1, 256):
        est &= separabilidad_(muestras_apuestas[i], muestras_apuestas[j], explicacion_del_modelo(10 , red_bidding, muestras_apuestas[i], atributos_prueba),  explicacion_del_modelo(10 , red_bidding, muestras_apuestas[j], atributos_prueba))
        #print("Separabilidad: Hasta los " ,j, " primeros está en:", est)
    #print("Separabilidad: Hasta los " ,i+1 , " primeros está en:", est)
print(est)

KeyboardInterrupt: 

In [190]:
# Metricas con randomForest de vinos
sel = 0.0

sel = selectividad_(muestras_apuestas,9, red_bidding)
print(sel)


C:\Users\Ale\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Users\Ale\anaconda3\lib\site-packages\numpy\core\_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


nan
0.6948818897637795
0.6948818897637795
0.7716202378111827
0.7716202378111827
0.6073773773037606
0.5515893624010854
0.5515893624010854
0.5883670433740377
0.5883670433740377


In [218]:
co = 0.0
cohe = []
# Red de apuestas (REVISAR PORQUE NO SE ELIMINAN LAS CARACTERISTICAS MENOS IMPORTANTES)
for j in range(0, 256):
    prediccion_original = red_bidding.predict(muestras_apuestas)
    muestras_modificadas = np.copy(muestras_apuestas)
    # Eliminacio de caracteristicas no importantes para red de apuestas
    muestras_modificadas[:, 0] = 0
    muestras_modificadas[:, 6] = 0
    muestras_modificadas[:, 7] = 0
    prediccion_nueva = red_bidding.predict(muestras_modificadas)
    co = coherencia_(prediccion_original[j], prediccion_nueva[j], objetivo_apuestas[j])
    cohe.append(co)
    print(co)
    print("EPOCA 1")

8/8 [==============================] - 0s 1ms/step
[0.00233317]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[1.1525117e-08]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00023403]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01604527]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01739431]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.12408412]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.03926865]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00383865]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.0093098]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01062313]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.0022702]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01141123]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00194399]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.0149191]


8/8 [==============================] - 0s 1ms/step
[0.12172049]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00015293]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01136433]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.0127858]
EPOCA 1
8/8 [==============================] - 0s 3ms/step
[0.00059297]
EPOCA 1
8/8 [==============================] - 0s 3ms/step
[0.3324578]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.0419815]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.01115107]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.04461839]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.17999113]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.24940382]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00061346]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00116241]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01304078]
EPO

8/8 [==============================] - 0s 2ms/step
[0.00557505]
EPOCA 1
8/8 [==============================] - 0s 3ms/step
[0.00050762]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.000134]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.01524867]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00653597]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.0001214]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00322865]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00022931]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00019317]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[2.5456771e-05]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.0032784]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00454108]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00083464]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00069242]
E

8/8 [==============================] - 0s 1ms/step
[5.9123617e-05]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00140708]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00067704]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00031994]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.0008117]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00749973]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00119529]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00066942]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.00060369]
EPOCA 1
8/8 [==============================] - 0s 2ms/step
[0.226888]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00058164]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00291896]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.00064186]
EPOCA 1
8/8 [==============================] - 0s 1ms/step
[0.20202827]


In [232]:
prediccion_original = red_bidding.predict(muestras_apuestas)
explicacion_error = []

for i in range(0, 256):
    exp = explicacion_del_modelo(10,red_bidding, muestras_apuestas[i], muestras_apuestas)
    exp2 = explicacion_del_modelo(10,red_bidding, muestras_modificadas[i], muestras_modificadas)
    explicacion_error.append(np.abs(exp - exp2))
explicacion_error = np.mean(explicacion_error)
completitud_(prediccion_original,explicacion_error, objetivo_apuestas)

8/8 [==============================] - 0s 1ms/step
[[0.01088606 0.01088606 0.01088606 ... 0.01088606 0.01088606 0.01088606]
 [0.00151158 0.00151158 0.00151158 ... 0.00151158 0.00151158 0.00151158]
 [0.00503467 0.00503467 0.00503467 ... 0.00503467 0.00503467 0.00503467]
 ...
 [0.00421942 0.00421942 0.00421942 ... 0.00421942 0.00421942 0.00421942]
 [0.02459723 0.02459723 0.02459723 ... 0.02459723 0.02459723 0.02459723]
 [0.00687025 0.00687025 0.00687025 ... 0.00687025 0.00687025 0.00687025]]
--------------------------------------------
0.11162668762637246


array([[10.2540944 , 10.2540944 , 10.2540944 , ..., 10.2540944 ,
        10.2540944 , 10.2540944 ],
       [73.84772929, 73.84772929, 73.84772929, ..., 73.84772929,
        73.84772929, 73.84772929],
       [22.17160888, 22.17160888, 22.17160888, ..., 22.17160888,
        22.17160888, 22.17160888],
       ...,
       [26.45547661, 26.45547661, 26.45547661, ..., 26.45547661,
        26.45547661, 26.45547661],
       [ 4.53818203,  4.53818203,  4.53818203, ...,  4.53818203,
         4.53818203,  4.53818203],
       [16.24783768, 16.24783768, 16.24783768, ..., 16.24783768,
        16.24783768, 16.24783768]])

In [219]:
congruencia_(cohe)

0.0011490179107524069